language: objective-c
osx_image: xcode11.3
before_install: gem install bundler --version '2.0.1'
install:
  - bundle install
jobs:
  exclude:
    if: type = pull_request AND branch = develop
  include:
    - stage: test
      script:
        - fastlane test
    - stage: pod-lint
      script:
        - pod lib lint
    - stage: deploy
      script:
        - fastlane publish_pod
stages:
  - test
  - pod-lint
  - name: test-lint
    if: type = pull_request
  - name: deploy
    # require the type to be a push to specific branch
    if: type = push AND branch = develop